version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
    command: python -m backend.wsgi
    ports:
      - "5500:5500"
    volumes:
      - ./backend:/app/backend
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@db:5432/heroleague
      API_KEY: ${API_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      FRONTEND_URL: ${FRONTEND_URL}
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      # passed into Vite at build/run time
      VITE_BACKEND_ORIGIN: http://backend:5500

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: heroleague
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
