"""add heroes table

Revision ID: 0a23ec9b4442
Revises: 7907949c6bdf
Create Date: 2025-10-01 18:01:35.782238

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0a23ec9b4442"
down_revision = "7907949c6bdf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "heroes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("image", sa.String(length=256), nullable=True),
        sa.Column("powerstats", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("biography", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("appearance", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("work", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("connections", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("heroes")
    # ### end Alembic commands ###
