"""Auto migration

Revision ID: 25bfb0a6ca4c
Revises: b444d0248f20
Create Date: 2025-10-01 21:53:06.772525

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "25bfb0a6ca4c"
down_revision = "b444d0248f20"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("heroes", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("full_name", sa.String(length=128), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("heroes", schema=None) as batch_op:
        batch_op.drop_column("full_name")

    # ### end Alembic commands ###
