"""Auto migration

Revision ID: b444d0248f20
Revises: 0a23ec9b4442
Create Date: 2025-10-01 19:59:23.566600

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b444d0248f20"
down_revision = "0a23ec9b4442"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("heroes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("alias", sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column("alignment", sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("heroes", schema=None) as batch_op:
        batch_op.drop_column("alignment")
        batch_op.drop_column("alias")

    # ### end Alembic commands ###
